### ISSUE TITLE
Error while building on React Native Android

### ISSUE THREAD

**Issue by YoucefBen47** [THEOplayer/react-native-theoplayer#10]
I was facing an error while building on Android that says duplicate classes. I commented this in the build.gradle file of react-native-theoplayer:
 implementation fileTree(include: ['*.jar', '*.aar'], dir: 'libs') and now I'm getting another error that says:
    More than one file was found with OS independent path 'META-INF/fragment_release.kotlin_module'.
Thank you.

**Comment by YoucefBen47** [comment]
After adding these to the packaginOptions it's building successfully.
        exclude 'META-INF/fragment_release.kotlin_module'
        exclude 'META-INF/activity_release.kotlin_module'
        exclude 'META-INF/lifecycle-viewmodel_release.kotlin_module'
        exclude 'META-INF/annotation-experimental_release.kotlin_module'

**Comment by tvanlaerhoven** [comment]
@YoucefBen47 The duplicate dependency is indeed solved by removing reference to any local aar's, like also mentioned in this PR: https://github.com/THEOplayer/react-native-theoplayer/pull/7.

Concerning the exclusion of the Kotlin manifest files: I guess you have dependencies that package duplicate conflicting manifest files. Can you track in which modules they are contained? Also, this is during building your own application, not the example app, right?

**Comment by tvanlaerhoven** [comment]
@YoucefBen47 Is it OK to close this issue, as we had an offline session yesterday?

**Comment by YoucefBen47** [comment]
@tvanlaerhoven Yes you can close it thank you. I actually submitted this issue so that it helps others who may have faced the same issue .
