### ISSUE TITLE
Add info on transitive dependencies

### ISSUE THREAD

**Issue by robbeman** [THEOplayer/react-native-theoplayer#103]
Autolinking does not work on transitive dependencies:
https://github.com/react-native-community/cli/issues/1347

So when installing this package you might be missing react-native bindings to some components used in the player UI. The simplest fix is to just add them as a root dependency as well.

```
yarn add react-native-svg @react-native-community/slider
```

Maybe adding this info to `creating-minimal-app.md` is enough?

**Comment by tvanlaerhoven** [comment]
@robbeman Thanks for pointing this out. We'll update our documentation indeed.
This dependency comes from our react-native UI, a component that currently is still part of this repository but will be extracted to a separate repo/module.
