### ISSUE TITLE
Conflicting frameworks googlecast.xcframework

### ISSUE THREAD

**Issue by janvandertaelen** [THEOplayer/react-native-theoplayer#106]
When installing version 2.3.0 with config

`{
	"ios": {
		"features": [
			"GOOGLE_IMA",
			"CHROMECAST"
		]
	}
}
` 
We get the error when we run pod install

`target has frameworks with conflicting names: googlecast.xcframework.`

When we remove CHROMECAST from the features pod install completes

**Comment by wvanhaevre** [comment]
Are you using any packages that also add a dependency to the Google Cast SDK? 

Our **_THEOplayerGoogleCastIntegration_** module adds a dependency to **google-cast-sdk-dynamic-xcframework**, which is a custom cocoapod setup to deliver the Google SDK with M1 support and underlying features like guest mode. If you are for instance depending on _react-native-google-cast_, which uses a different Google Cast cocoapod setup (**google-cast-sdk-dynamic-xcframework-nobluetooth**) both dependencies add the googlecast.xcframework as a vendored_framework, which clashes.

**Comment by wvanhaevre** [comment]
This should be solved through: https://github.com/THEOplayer/react-native-theoplayer/blob/master/doc/cast.md#combining-with-react-native-google-cast

**Comment by wvanhaevre** [comment]
Confirmed by reporter.
