### ISSUE TITLE
No controls on Android !!

### ISSUE THREAD

**Issue by YoucefBen47** [THEOplayer/react-native-theoplayer#11]
On iOS when chromeless it set to false the controls are there. on Android there are no controls whether chromeless is set to true or false. 
Also there is no back arrow to exit the player.

**Comment by tvanlaerhoven** [comment]
@YoucefBen47 The native UI for the Android SDK is still under development. It is expected in the coming months. So, for the moment, on Android there's only the ReactNative UI. We'll keep you updated here.

**Comment by YoucefBen47** [comment]
How can I add controls to the ReactNative UI ? I tried adding the Android SDK's sample UI but the app crashes

**Comment by KestasVenslauskas** [comment]
@tvanlaerhoven Is there any progress on this issue?
Settings chromeless true/false on android makes no difference - there is still no controls.
