### ISSUE TITLE
iOS & tvOS build fails with version 2.4.0

### ISSUE THREAD

**Issue by janvandertaelen** [THEOplayer/react-native-theoplayer#110]
If we try to make build with version 2.4.0 Xcodes throws an error

`Failed to build module 'THEOplayerGoogleCastIntegration'; this SDK is not supported by the compiler (the SDK is built with 'Apple Swift version 5.3.2 (swiftlang-1200.0.45 clang-1200.0.32.28)', while this compiler is 'Apple Swift version 5.7.2 (swiftlang-5.7.2.135.5 clang-1400.0.29.51)'). Please select a toolchain which matches the SDK.`

We also didn't include CHROMECAST in the react-native-theoplayer.json

```
{
	"ios": {
		"features": [
			"GOOGLE_IMA"
		]
	}
}
```

Xcode version 14.2

**Comment by wvanhaevre** [comment]
The THEOplayerGoogleCastIntegration is delivered through the THEOplayer-Integration-GoogleCast cocoapod which is only added as a dependency to your project if you put the CHROMECAST flag in the react-native-theoplayer.json: 
```
if theofeatures.include?("CHROMECAST")
      puts "Adding THEOplayer-Integration-GoogleCast"
      s.ios.dependency "THEOplayer-Integration-GoogleCast"
end
```

Could you verify by removing all pods and doing a new pod install/update?

**Comment by wvanhaevre** [comment]
Closed as non active ticket. Not reported on later versions.
