### ISSUE TITLE
PlayerEventType.BUFFERING_CHANGE mentioned in docs doesn't exists

### ISSUE THREAD

**Issue by bpkmatthiasv** [THEOplayer/react-native-theoplayer#115]
Hello, the [documentation](https://github.com/THEOplayer/react-native-theoplayer/blob/develop/doc/theoplayerview-component.md#buffering-state-changes) mentions the `PlayerEventType.BUFFERING_CHANGE` event to listen to buffering changes but it is not part of the [enum](https://github.com/THEOplayer/react-native-theoplayer/blob/629a32d0d764a0ccd2fbaf49593606ef31cce919/src/api/player/PlayerEventMap.ts#L18).

My aim was to detect buffering stalls, should I use the PlayerEventType.WAITING instead ?

Thanks in advance for your feedback

Matthias

**Comment by tvanlaerhoven** [comment]
@bpkmatthiasv you're right, this is a left over from the 1.8 API, thanks for point this out. We'll fix it.

**Comment by tvanlaerhoven** [comment]
Documentation was updated:
https://github.com/THEOplayer/react-native-theoplayer/blob/develop/doc/theoplayerview-component.md
Thanks @bpkmatthiasv
