### ISSUE TITLE
textTrackStyle for iOS/Android

### ISSUE THREAD

**Issue by kamilafsar** [THEOplayer/react-native-theoplayer#152]
Hi there,

First of all: great lib :)

We're currently evaluating if THEOplayer is the right way to go for us.
One potential blocker is that `textTrackStyle` is not available for iOS/Android according to the docs:
```
/**
 * The text track style API.
 *
 * @remarks
 * Only available for Web.
 */
readonly textTrackStyle: TextTrackStyle;
```

Is there some other way to achieve this? If not, are there any plans to support this? If so, is there a timeline for it?

Thanks!

**Comment by tvanlaerhoven** [comment]
Hi @kamilafsar , thanks for reaching out!

Indeed, the texttrack styling API of react-native-theoplayer is currently only available for Web, but the native iOS/Android SDKs already include this feature, so the remaining work is bridging it towards react-native.

We do not have this work on our roadmap currently, but we frequently adjust the planning based on customer needs. I'd suggest you contact us offline to see if we can work something out. I can bring you in contact with our sales team.
