### ISSUE TITLE
Android error on build (Unresolved reference: setAllowBackgroundPlayback)

### ISSUE THREAD

**Issue by davidwinograd1** [THEOplayer/react-native-theoplayer#179]
When I build my project in Android Studio, I get the following error:

e: /Users/.../.../.../node_modules/react-native-theoplayer/android/src/main/java/com/theoplayer/ReactTHEOplayerContext.kt: (123, 25): Unresolved reference: setAllowBackgroundPlayback

Would anyone happen to know what is causing this, and what the fix is? I haven't changed my code and have never gotten this. Using version 2.11...

**Comment by tvanlaerhoven** [comment]
@davidwinograd1 did this solve the issue for you?

**Comment by tvanlaerhoven** [comment]
Closing this ticket for now
