### ISSUE TITLE
Error while updating property 'source' of a view managed by: THEOplayerView

### ISSUE THREAD

**Issue by mohitbhansali** [THEOplayer/react-native-theoplayer#2]
Hi Team

I am using "08-rn-custom-ui" setup in my project, the app works fine in the debug mode, but as soon as I build the app in release mode, it crashes with the following error:

`Error while updating property 'source' of a view managed by: THEOplayerView`

Is there any proguard setting I have to enable?

**Comment by savdeepgandhi13** [comment]
Hello Mohit 

Can you share which platform you are referring to? (iOS or Android) so that it can be tested from our side.

Thanks

**Comment by mohitbhansali** [comment]
Hi, I am trying to integrate into the Android platform.

**Comment by savdeepgandhi13** [comment]
Hello Mohit, 

I have tried the same guided steps from the article, and did not faced any issue, Can you please make changes accordingly for signing configs in the build gradle. https://stackoverflow.com/questions/33802401/how-to-debug-the-android-app-in-release-mode-using-android-studio

if you still face issues, can you please log the error over here or an screenshot. 

Thanks
