### ISSUE TITLE
Too many logs causing the app to freeze for a few seconds.

### ISSUE THREAD

**Issue by YoucefBen47** [THEOplayer/react-native-theoplayer#22]
We are using the sample ui in our app and I noticed many logs on events. When enabling a subtitle there are about 50+ cue logs that cause the app to freeze until the logs are done. On the example app I can comment the prints but how can I do that on our app ? 
I only copied the example/src folder to our app. I tried copying the swift files but that changed nothing.
And also I implemented a play next functionality. on iOS when I play next episode it auto plays but on Android it stays paused.

**Comment by wvanhaevre** [comment]
Hi @YoucefBen47 , it looks like we forgot to disable the debug logging in our iOS Bridge when releasing the latest version of the package. I'll fix that and prepare an update today

**Comment by wvanhaevre** [comment]
The PR is merged and the fix will be part of the v1.5.0 release of the react-native-package

**Comment by wvanhaevre** [comment]
@YoucefBen47 Did you have a chance to check if the logging has been disabled successfully? If ok, we can close this ticket.

**Comment by YoucefBen47** [comment]
Did not test yet. I thought the logs will be disabled with the next
version. I will test in about an hour and let you know.
I have also posted another issue concerning the subtitles.

**Comment by wvanhaevre** [comment]
My mistake. Indeed, the log fix was not released yet
