### ISSUE TITLE
HH:MM:SS timestamps do not work for IMA ads on iOS

### ISSUE THREAD

**Issue by webnard** [THEOplayer/react-native-theoplayer#220]
On iOS, setting an ad like this does not work

```jsx
    {
      integration: 'google-ima' as AdIntegrationKind,
      sources: {
        src: 'https://cdn.theoplayer.com/demos/preroll.xml',
        type: 'vast',
      },
      timeOffset: "00:00:10",
    },
```

 For the above to work, it must be converted to a number type: `timeOffset: 10`

Android works fine in both instances.

**Comment by wvanhaevre** [comment]
Confirmed. Our underlying native iOS SDK only supports the following timeOffset formats:
- a number for the offset in seconds.
- "start" for a preroll.
- "end" for a postroll
- a percentage string (XX%) for a proportion of the content duration.

We will update the iOS SDK to also support the missing format. In the meantime a quick conversion from the timeString to the number value (seconds) could serve as a workaround.

**Comment by wvanhaevre** [comment]
@webnard Since the 6.6.0 release, our iOS SDK also supports Timecode strings (HH:mm:ss.SSS) to set the offset for an ad. As a result our react-native-theoplayer also has that functionality now If you make sure the underlying sdk is updated to the latest version.
