### ISSUE TITLE
Android PIP layout is broken

### ISSUE THREAD

**Issue by KestasVenslauskas** [THEOplayer/react-native-theoplayer#225]
When trying to use PIP on android while player is not a fullscreen view it renders just the top of the screen:

<img width="261" alt="image" src="https://github.com/THEOplayer/react-native-theoplayer/assets/52245569/103d48dc-15b1-40f4-bdc9-1fd2bb9051e8">

**Here is that screen:**
<img width="270" alt="image" src="https://github.com/THEOplayer/react-native-theoplayer/assets/52245569/523cb61c-cb3b-4fef-a65e-9913b9f93621">

**Comment by tvanlaerhoven** [comment]
Hi @KestasVenslauskas ,

The PiP presentation mode gets the visible rectangle of the player screen and passes this to the PiP parameters when transitioning to PiP.

https://github.com/THEOplayer/react-native-theoplayer/blob/develop/android/src/main/java/com/theoplayer/presentation/PipUtils.kt#L198

So I wouldn't expect to see the action bar here. Can you check if the visible rectangle is computed correctly here? As a workaround you could also experiment with hiding/showing the action bar when transitioning to/from PiP.

Additionally, you can also contact us through the service desk to pass some relevant app code. In that case the issue will flow through our regular defect flow.

**Comment by KestasVenslauskas** [comment]
Everyting works fine if I make a full screen layout will test different layouting options

**Comment by KestasVenslauskas** [comment]
@tvanlaerhoven 

So I tried to play around with layouts. To get the best results I tried to use as minimal layout as possible:
<img width="626" alt="image" src="https://github.com/THEOplayer/react-native-theoplayer/assets/52245569/3a243a79-cc98-45dd-8c4b-17649e249ed8">

My findings:

1. If a player is at the top of the screen & screen is without header so there is nothing above the player it works fine.
Rect(0, 66 - 1080, 673)
<img width="435" alt="image" src="https://github.com/THEOplayer/react-native-theoplayer/assets/52245569/8ef4831a-bd6e-4856-b52d-34a707af4d32">

2. I tried adding text "test" on over the video player.
Rect(0, 119 - 1080, 726)
<img width="476" alt="image" src="https://github.com/THEOplayer/react-native-theoplayer/assets/52245569/aee5d583-8e0b-4152-8849-faad21e833ee">

3. Added 2 more "test" texts on top & 2 "test" texts on bottom
Rect(0, 225 - 1080, 832)
<img width="471" alt="image" src="https://github.com/THEOplayer/react-native-theoplayer/assets/52245569/f7adba6c-e69b-4b66-af60-c9579b22f72c">

**Comment by tvanlaerhoven** [comment]
@KestasVenslauskas we'll take it up internally

**Comment by tvanlaerhoven** [comment]
Hey @KestasVenslauskas , following up on the issue above. Was this solved?
We do set a `sourceRectHint` in our code, as mentioned before, but this is only for the transition from/to PiP. The screen's layout needs to make sure no other UI elements are visible:
https://developer.android.com/develop/ui/views/picture-in-picture#best

> PiP is intended for activities that play full-screen video. When switching your activity into PiP mode, avoid showing anything except video content. Track when your activity enters PiP mode and hide UI elements, as described in [Handling UI during PiP](https://developer.android.com/develop/ui/views/picture-in-picture#handling_ui).

So in the example above, the "test" Text element would need to be hidden in PiP mode:
`{presentationMode !== PresentationMode.pip && <Text>test</Text>}`

**Comment by tvanlaerhoven** [comment]
@KestasVenslauskas closing this ticket for now. Let us know in case you need additional support.
