### ISSUE TITLE
onDurationChange reports duration in seconds on iOS, but in milliseconds on Android

### ISSUE THREAD

**Issue by IjzerenHein** [THEOplayer/react-native-theoplayer#24]
It appears the `duration` is mis-reported in iOS/tvOS. On nearly all instances, the currentTime and duration are reported in milliseconds. However on iOS/tvOS the duration is reported in Seconds instead. This causes time progress indicators to display the duration incorrectly.

tvOS:

![image](https://user-images.githubusercontent.com/6184593/186168655-b7be9e06-14e1-40e9-980c-95eeb1fb5670.png)

Android:

<img width="346" alt="image" src="https://user-images.githubusercontent.com/6184593/186168553-e7781e53-ffbf-46b4-89bb-6c99492ee2b8.png">

Problem is most likely caused by a missing multiplication in:
https://github.com/THEOplayer/react-native-theoplayer/blob/develop/ios/THEOplayerRCTViewEventHandler.swift#L148

**Comment by kevin-kp** [comment]
@IjzerenHein 

We saw the same thing but in the opposite way.
Almost all values are set to milliseconds except the duration on iOS/tvOS.
If you look at the value of PROGRESS or TIME_UPDATE  in both iOS and Android, you can see that all values are converted to milliseconds except the duration on iOS/tvOS.

Examples:
Android:
TIME_UPDATE: https://github.com/THEOplayer/react-native-theoplayer/blob/develop/android/src/main/java/com/theoplayer/VideoEventEmitter.java#L270
PROGRESS: https://github.com/THEOplayer/react-native-theoplayer/blob/develop/android/src/main/java/com/theoplayer/VideoEventEmitter.java#L307
DURATION: https://github.com/THEOplayer/react-native-theoplayer/blob/develop/android/src/main/java/com/theoplayer/VideoEventEmitter.java#L286

iOS:
PROGRESS: https://github.com/THEOplayer/react-native-theoplayer/blob/develop/ios/THEOplayerRCTViewEventHandler.swift#L164
TIME_UPDATE: https://github.com/THEOplayer/react-native-theoplayer/blob/develop/ios/THEOplayerRCTViewEventHandler.swift#L183

DURATION that is not multiplied: https://github.com/THEOplayer/react-native-theoplayer/blob/develop/ios/THEOplayerRCTViewEventHandler.swift#L148

Not sure why all your values seem to be seconds, but normally they all should be in milliseconds

**Comment by IjzerenHein** [comment]
@kevin-kp You are absolutely right. I made a silly mistake and overlooked a part in my code where I did some normalisation on the time values. I'll update the issue and PR accordingly 👍

**Comment by wvanhaevre** [comment]
@kevin-kp, @IjzerenHein thanks for reporting and investigating! The fix will be available in our next release.
