### ISSUE TITLE
A failure occurred while executing org.jetbrains.kotlin.compilerRunner.GradleCompilerRunnerWithWorkers$GradleKotlinCompilerWorkAction

### ISSUE THREAD

**Issue by davidwinograd1** [THEOplayer/react-native-theoplayer#251]
@tvanlaerhoven @wvanhaevre 

Would anyone know what the issue is when I run my theoplayer project in Android Studio?

"react-native-theoplayer": "^3.4.2",

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':react-native-theoplayer:compileDebugKotlin'.
A failure occurred while executing org.jetbrains.kotlin.compilerRunner.GradleCompilerRunnerWithWorkers$GradleKotlinCompilerWorkAction
Compilation error. See log for more details

For additional context, the same issue seems to be happening in another repo as well:
https://github.com/wix/react-native-navigation/issues/7818

**Comment by tvanlaerhoven** [comment]
Hey @davidwinograd1 , could you post the full error log here?

**Comment by tvanlaerhoven** [comment]
@davidwinograd1 , aha it looks like the compiler can't find `track` parameter in `EnterCueEvent` and ExitCueEvent` here
https://github.com/THEOplayer/react-native-theoplayer/blob/develop/android/src/main/java/com/theoplayer/PlayerEventEmitter.kt#L440

It looks like you are depending on an older version of the native THEOplayer sdk. Make sure you target at least Android SDK 6.5.0 (https://docs.theoplayer.com/changelog.md#-features-8)

**Comment by davidwinograd1** [comment]
worked -- thank you!

**Comment by tvanlaerhoven** [comment]
👍
