### ISSUE TITLE
Version 3.7.1 gives a React Render Error

### ISSUE THREAD

**Issue by michelecocuccio** [THEOplayer/react-native-theoplayer#261]
Hello,
I upgraded from version 3.6.0 to 3.7.1, removed node_modules, ios and android folder and did a clean build.

Now, the `<THEOPlayerView />` component throws an error as it returns `undefined` somewhere.
I have tried with a basic example and it sill gives the same error.

You can view  a video here [video here](https://www.awesomescreenshot.com/video/25009489?key=d4a12f8993c668079a1b3789cc44f070
)

![Simulator Screenshot - iPhone 15 Pro - 2024-02-16 at 17 05 05](https://github.com/THEOplayer/react-native-theoplayer/assets/8071249/80ac1520-2f41-4bd5-96e8-29695bd41341)

```
    "@theoplayer/react-native-analytics-youbora": "^1.1.1",
    "@theoplayer/react-native-ui": "^0.4.0",
    "react-native-theoplayer": "3.7.1",
```
I am using Expo 50 but it doesn't seems an Expo related issue

**Comment by michelecocuccio** [comment]
I think the culprit could be `react-native 0.73.4`. I will do further test and let you know.

**Comment by tvanlaerhoven** [comment]
@michelecocuccio in this PR we upgrade the dependencies & example app to RN v0.73.4:

https://github.com/THEOplayer/react-native-theoplayer/pull/264

**Comment by michelecocuccio** [comment]
> @michelecocuccio in this PR we upgrade the dependencies & example app to RN v0.73.4:
> 
> #264

thank you very much for the fast response!
