### ISSUE TITLE
Android: application/x-mpegurl format loading issues

### ISSUE THREAD

**Issue by KestasVenslauskas** [THEOplayer/react-native-theoplayer#27]
WIth TheoPlayer SDK v4.0 it's possible to run application/x-mpegurl video streams. But the issue is that it does not load some video files. 
Basically if the video is not a live stream it's not loaded. But if I try to run a livestream it get loaded but after 10-15 seconds and after starting playing it buffers frequently. My internet connection is stable and should not be an issue here.

I tried some of the sources from example project with type:'application/x-mpegurl' but was not able to load the video.
But the livestream source did load, I used [this](https://lrthd.lrt.lt/secure/lrt_hd/hls/it17fc4H067BGe7gMPjyog/1662996223/lrt_televizija.m3u8) one.

**Comment by Danesz** [comment]
Hi @KestasVenslauskas,

Thank you for your feedback.

Do you use the react-native SDK on a web environment or do you have a problem with native apps?

Did it work before THEOplayer 4.0? Could you please verify it?
THEOplayer 4.0 introduced a new HLS pipeline (https://docs.theoplayer.com/changelog.md#-breaking-changes), maybe this could be the issue. You could try to set `useLegacy` if you have access to a custom SDK too.

Thank you in advance!

**Comment by KestasVenslauskas** [comment]
Hi @Danesz the issue is on Android only as per title. Sorry that I was not clear with the description.
Before v4.0 video stream gave us an error because format was not supported yet as I was told from Theo team.

**Comment by tvanlaerhoven** [comment]
@KestasVenslauskas The player responds with a 403 status error, indicating the manifest could not be retrieved. Is it perhaps geo-restricted, or not available anymore?

**Comment by KestasVenslauskas** [comment]
@tvanlaerhoven It was definetely available at the time. I also tested many video sources from our side. But I need to ask about geo-restrictions.

**Comment by tvanlaerhoven** [comment]
@KestasVenslauskas Could you check again with the [latest release](https://github.com/THEOplayer/react-native-theoplayer/releases/tag/v1.6.0)?
There was indeed an issue with play-back of HLS streams that has been fixed.

**Comment by KestasVenslauskas** [comment]
@tvanlaerhoven Looking at 1.6.0 looks like it's fixed :)

**Comment by tvanlaerhoven** [comment]
Excellent! Thanks for notifying us @KestasVenslauskas 👌
