### ISSUE TITLE
GOOGLE_IMA SDK makes app crash in Android 14

### ISSUE THREAD

**Issue by michelecocuccio** [THEOplayer/react-native-theoplayer#273]
Hello,

we have noticed that any THEOPlayer video with IMA ads in it crashes on Android 14. After further inspection the culprit seems to be GOOGLE_IMA SDK. 

Below is the error and I think this is the key part (the writable dex file part). Upon looking online I have found this [Google Thread which recommend to update GOOGLE_IMA SDK to version v3.31.0](https://groups.google.com/g/ima-sdk/c/XCrb5a5WiYI?pli=1). 

```
02-29 14:33:56.522 14921 16152 E AndroidRuntime: java.lang.SecurityException: Writable dex file '/data/user/0/it.legabasket.app/cache/1633031840514.jar' is not allowed.
```

```
**02-29 14:33:56.522 14921 16152 E AndroidRuntime: FATAL EXCEPTION: pool-31-thread-3
02-29 14:33:56.522 14921 16152 E AndroidRuntime: Process: it.legabasket.app, PID: 14921
02-29 14:33:56.522 14921 16152 E AndroidRuntime: java.lang.SecurityException: Writable dex file '/data/user/0/it.legabasket.app/cache/1633031840514.jar' is not allowed.
02-29 14:33:56.522 14921 16152 E AndroidRuntime: 	at dalvik.system.DexFile.openDexFileNative(Native Method)
02-29 14:33:56.522 14921 16152 E AndroidRuntime: 	at dalvik.system.DexFile.openDexFile(DexFile.java:406)
02-29 14:33:56.522 14921 16152 E AndroidRuntime: 	at dalvik.system.DexFile.<init>(DexFile.java:128)
02-29 14:33:56.522 14921 16152 E AndroidRuntime: 	at dalvik.system.DexFile.<init>(DexFile.java:101)
02-29 14:33:56.522 14921 16152 E AndroidRuntime: 	at dalvik.system.DexPathList.loadDexFile(DexPathList.java:438)
02-29 14:33:56.522 14921 16152 E AndroidRuntime: 	at dalvik.system.DexPathList.makeDexElements(DexPathList.java:397)
02-29 14:33:56.522 14921 16152 E AndroidRuntime: 	at dalvik.system.DexPathList.<init>(DexPathList.java:166)
02-29 14:33:56.522 14921 16152 E AndroidRuntime: 	at dalvik.system.BaseDexClassLoader.<init>(BaseDexClassLoader.java:160)
02-29 14:33:56.522 14921 16152 E AndroidRuntime: 	at dalvik.system.BaseDexClassLoader.<init>(BaseDexClassLoader.java:105)
02-29 14:33:56.522 14921 16152 E AndroidRuntime: 	at dalvik.system.DexClassLoader.<init>(DexClassLoader.java:55)
02-29 14:33:56.522 14921 16152 E AndroidRuntime: 	at com.google.ads.interactivemedia.v3.internal.anw.t(IMASDK:28)
02-29 14:33:56.522 14921 16152 E AndroidRuntime: 	at com.google.ads.interactivemedia.v3.internal.anb.t(IMASDK:1)
02-29 14:33:56.522 14921 16152 E AndroidRuntime: 	at com.google.ads.interactivemedia.v3.internal.anb.v(IMASDK:2)
02-29 14:33:56.522 14921 16152 E AndroidRuntime: 	at com.google.ads.interactivemedia.v3.internal.anc.j(IMASDK:1)
02-29 14:33:56.522 14921 16152 E AndroidRuntime: 	at com.google.ads.interactivemedia.v3.internal.ana.j(IMASDK:2)
02-29 14:33:56.522 14921 16152 E AndroidRuntime: 	at com.google.ads.interactivemedia.v3.internal.ana.run(IMASDK:13)
02-29 14:33:56.522 14921 16152 E AndroidRuntime: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
02-29 14:33:56.522 14921 16152 E AndroidRuntime: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
02-29 14:33:56.522 14921 16152 E AndroidRuntime: 	at java.lang.Thread.run(Thread.java:1012)
02-29 14:33:56.524 14921 16151 E .legabasket.app: Attempt to load writable dex file: /data/user/0/it.legabasket.app/cache/1633031840514.jar
02-29 14:33:56.677 16174 16174 E android.dqagent: Not starting debugger since process cannot load the jdwp agen**
```

Is there anything that you can do to fix this? 

```
    "react-native": "0.72.10",
    "react-native-theoplayer": "3.8.0",
```

Thanks

**Comment by tvanlaerhoven** [comment]
@michelecocuccio could you check you are targeting at least the Android player SDK v6.6.0? There was a related Android 14 fix in this release:
https://docs.theoplayer.com/changelog.md#android-5

**Comment by michelecocuccio** [comment]
@tvanlaerhoven hello thanks fo you reply.
What do you mean by targeting Android Player SDK 6.6.0? I saw the changelog that you posted (thank you for the reference) but I assume it's related to theoplayer version, which should be used by react-native-theoplayer. Is that correct? I also upgraded react-native-theoplayer to the last version this morning but the crash still happen.

I am building my app with a `targetSdkVersion` of `34` which supports Android 14. I am building my react-native / expo app with Android Studio. Gradle version is 8.2 and the build goes smoothly. 

I personally don't know where to look for Android Player SDK. I was assuming everything was handled by react-native-theoplayer. 

Thanks

**Comment by michelecocuccio** [comment]
@tvanlaerhoven I just checked that `react-native-theoplayer` has `theoplayer` version 3.5.0 as dependency. I think this is the cause.
<img width="535" alt="Screenshot 2024-03-11 at 09 27 42" src="https://github.com/THEOplayer/react-native-theoplayer/assets/8071249/597a4c25-e548-44b4-b8cf-213c522d5260">

**Comment by tvanlaerhoven** [comment]
@michelecocuccio the NPM theoplayer dependency is for the Web-based SDK; to forcefully set the Android version you should use the `THEOplayer_sdk` property in your `gradle.properties` file (https://github.com/THEOplayer/react-native-theoplayer/blob/develop/doc/creating-minimal-app.md#getting-started-on-android)

Normally the latest Android player SDK version will be chosen. Did you maybe pin it to an earlier version in your `gradle.properties` file?

**Comment by tvanlaerhoven** [comment]
Hey @michelecocuccio, did this last suggestion solve your issue?

**Comment by michelecocuccio** [comment]
Hello @tvanlaerhoven. Unfortunately I have been sick and I couldn't work on the project but I ended up solving it by patching react-native-theoplayer by adding `implementation 'com.google.ads.interactivemedia.v3:interactivemedia:3.32.0'` in the `build.gradle` file. I will test it as soon as I get back to work. Sorry for the delay in the response and thank you for providing assistance. Please feel free to close the issue for now if you think is right.

Many thanks

**Comment by tvanlaerhoven** [comment]
@michelecocuccio we also upgraded the IMA dependency version in player SDK v6.12.0; so make sure to at least target this version.
 & Take care!
