### ISSUE TITLE
DRM content-protected won't play on tvOS/Android TV

### ISSUE THREAD

**Issue by danychi** [THEOplayer/react-native-theoplayer#29]
Hi there, I would like to start by saying thank you so much for this library, and thanks to the maintainer for working hard in adding support to all platforms ❤️❤️
 
Currently, I am having an issue when trying to play DRM content-protected videos on tvOS/Android TV. 

I am using:
- react-native-tvos@0.68.2-3
- react-native-theoplayer@1.3.0
- TheoPlayerSDK@3.5.0 on tvOS
- TheoPlayerSDK@3.7.0 on Android TV

I'm providing the following sources to THEOplayer:
```ts
const url = Platform.select({
    ios: hlsUrl ?? dashUrl,
    android: dashUrl ?? hlsUrl,
});

const sourceContentProtection: DRMConfiguration = {
        integration: 'keyos',
        fairplay: {
            licenseAcquisitionURL: XXXXXXXX,
            certificateURL: YYYYYYYYY,
        },
        // some custom protection data generated by our backend
        ...(authXML && {
            customdata: authXML,
        }),
    };

const source: Sources | undefined = url
    ? {
          type:
              url === dashUrl
                  ? 'application/dash+xml'
                  : 'application/x-mpegurl',
          src: url,
          contentProtection: sourceContentProtection,
      }
    : undefined;

....
return(
  <THEOplayerView
      source={{
          sources: source ? [source] : [],
      }}
  />
)
```

Android TV is reporting the following error:
```
Error during license server request
```
![Screenshot 2022-09-13 at 15 40 51](https://user-images.githubusercontent.com/45874461/189916763-29f349b5-9e69-467a-8f7b-d9d246ea1828.png)

tvOS instead:
```
Something went wrong while trying to play the content.
```
![Simulator Screen Shot - Apple TV - 2022-09-13 at 15 40 56](https://user-images.githubusercontent.com/45874461/189916726-5cd2bf21-cd21-4ba1-b803-e78b9dc78fe6.png)

Note that the same stream is playing perfectly on THEOplayer web and that other not DRM content-protected videos are working perfectly on this tvOS and Android TV 📺

**Comment by tvanlaerhoven** [comment]
Hey @danychi, many thanks for feedback! Support for pre-integrated DRM configurations (such as KeyOS) was indeed still missing from the Android bridge. It is added in this [PR](https://github.com/THEOplayer/react-native-theoplayer/pull/30), and will be part of the next release.

**Comment by wvanhaevre** [comment]
For iOS/tvOS we found an issue on the RN bridge where we missed processing the customdata from the keyos. That is also fixed in a branch that we are currently working on and will be merged into the next release.

**Comment by danychi** [comment]
@wvanhaevre Android TV is working when using `react-native-theoplayer@1.6.1`, but the issue remains on tvOS.

What is the status of the fix for tvOS? 📺 

Thanks!!!

**Comment by ceyhun-o** [comment]
Hi @danychi,

As I mentioned on the internal ticket you created (THEOSD-12374), this is working without issues on our side. Let's continue our investigation on the internal ticket to see what might be going wrong here.

Kind regards,
Ceyhun
