### ISSUE TITLE
Reloading iOS/tvOS app causes exception when removing TextTrack event listeners

### ISSUE THREAD

**Issue by IjzerenHein** [THEOplayer/react-native-theoplayer#3]
First of all, thank you so much for this library, we (the community) really appreciate all the hard work put into this and the dedication of THEOPlayer to support the react-native platform ❤️  ❤️ 

To reproduce:
- Launch the iOS or tvOS example app
- Press Ctrl+R to reload the app
- Exception occurs in native code when calling `player.textTracks.removeEventListener`

![image](https://user-images.githubusercontent.com/6184593/175328776-127b6060-80e5-4330-8f35-259db68415a4.png)

Investigated:
- Out-commenting the whole content of `dettachTextTrackListListeners` prevents the exception from happening

**Comment by wvanhaevre** [comment]
Fix merged on develop.
