### ISSUE TITLE
Android build error: Execution failed for task ':react-native-theoplayer:compileDebugKotlin'

### ISSUE THREAD

**Issue by davidwinograd1** [THEOplayer/react-native-theoplayer#347]
"react-native": "0.68.7",
 "react-native-theoplayer": "^7.6.0", (but also happens on 7.4.0)
  kotlinVersion = "1.9.0"
  
<img width="1627" alt="Screenshot 2024-07-01 at 3 36 10 PM" src="https://github.com/THEOplayer/react-native-theoplayer/assets/123401159/df6067ee-54d4-415b-9849-2e81d3a8e09b">

Would love to know if anyone has any feedback or solutions! Let me know if you have any questions about a version of anything I'm using

@tvanlaerhoven

**Comment by tvanlaerhoven** [comment]
Hey @davidwinograd1 , we indeed had an unintentional API change in our native Android player SDK. It was a breaking change as it added an abstract method to some Ad classes. For that reason, if you'd upgrade to react-native-theoplayer v7.4.0 or higher, you would have to combine this with an Android player SDK 7.6.0+.

We included this dependency constraint in the SDK's gradle file:
https://github.com/THEOplayer/react-native-theoplayer/blob/develop/android/build.gradle#L116

Could it be you have pinned your Android player SDK to a lower version in the gradle.properties?
https://github.com/THEOplayer/react-native-theoplayer/blob/develop/example/android/gradle.properties#L44
 
If so, please upgrade here.

**Comment by davidwinograd1** [comment]
Got it! Yes it was on a lower SDK Android version. @tvanlaerhoven 

I added this to my gradle.properties:
THEOplayer_sdk = 7.6.0

But then I get the error below...any ideas?

<img width="1607" alt="Screenshot 2024-07-02 at 5 27 11 PM" src="https://github.com/THEOplayer/react-native-theoplayer/assets/123401159/93de9c0e-3714-4a50-bfb4-0cf69fdba5b4">

**Comment by davidwinograd1** [comment]
Fixed! Thank you!

**Comment by tvanlaerhoven** [comment]
@davidwinograd1 OK good to hear!
