### ISSUE TITLE
[Question] : continue playing videos when screen is locked

### ISSUE THREAD

**Issue by FacundoLastra** [THEOplayer/react-native-theoplayer#35]
Hi! i want to ask if exist the possibility to continue playing videos when the screen is locked, on my implementation when the screen is lock the player pause automatically.

Thanks!

**Comment by tvanlaerhoven** [comment]
Hey @FacundoLastra ! The player's lifecycle is now closely coupled to the app state indeed. So if the app goes to the background, the player will pause.

We have a background-playback on our roadmap in the next few months. So it will be available then.
