### ISSUE TITLE
DRM content-protected won't play on tvOS

### ISSUE THREAD

**Issue by danychi** [THEOplayer/react-native-theoplayer#38]
Hi there, I'm creating this issue to report that I cannot play DRM content-protected videos on tvOS

I am using:
```
react-native-tvos@0.69.5-1
react-native-theoplayer@1.6.1
TheoPlayerSDK@3.7.0 on tvOS
```
I'm providing the following sources to THEOplayer:
```ts
const url = Platform.select({
    ios: hlsUrl ?? dashUrl,
    android: dashUrl ?? hlsUrl,
});

const sourceContentProtection: DRMConfiguration = {
        integration: 'keyos',
        fairplay: {
            licenseAcquisitionURL: XXXXXXXX,
            certificateURL: YYYYYYYYY,
        },
        // some custom protection data generated by our backend
        ...(authXML && {
            customdata: authXML,
        }),
    };

const source: Sources | undefined = url
    ? {
          type:
              url === dashUrl
                  ? 'application/dash+xml'
                  : 'application/x-mpegurl',
          src: url,
          contentProtection: sourceContentProtection,
      }
    : undefined;

....
return(
  <THEOplayerView
      source={{
          sources: source ? [source] : [],
      }}
  />
)
```
tvOS is reporting the following error:

```
Something went wrong while trying to play the content.
```
![image](https://user-images.githubusercontent.com/45874461/197183841-2206c3a4-ada7-4817-a083-7392b36144d5.png)

Note that the same stream is playing perfectly on THEOplayer web and that other not DRM content-protected videos are working perfectly on this tvOS  📺

Related to issue #29

**Comment by ceyhun-o** [comment]
Hi @danychi,

As I mentioned on the internal ticket you created (THEOSD-12374), this is working without issues on our side. Let's continue our investigation on the internal ticket to see what might be going wrong here.

I will be closing this issue now.

Kind regards,
Ceyhun
