### ISSUE TITLE
Android application crash on newest version

### ISSUE THREAD

**Issue by Veryyapeee** [THEOplayer/react-native-theoplayer#393]
React-native-theoplayer version: 8.0.3
Android SDK: newest

While launching player on AndroidTV, app crashes which these logs:

`09-13 14:39:08.959 14200 14200 E AndroidRuntime: FATAL EXCEPTION: main
09-13 14:39:08.959 14200 14200 E AndroidRuntime: Process: com.backscreenapp, PID: 14200
09-13 14:39:08.959 14200 14200 E AndroidRuntime: java.lang.NoClassDefFoundError: Failed resolution of: [Lcom/theoplayer/android/api/ads/ima/GoogleImaAdEventType;
09-13 14:39:08.959 14200 14200 E AndroidRuntime:        at com.theoplayer.android.api.ads.wrapper.AdsApiWrapper.<clinit>(SourceFile:1)
09-13 14:39:08.959 14200 14200 E AndroidRuntime:        at com.theoplayer.ReactTHEOplayerView.<init>(ReactTHEOplayerView.kt:40)
09-13 14:39:08.959 14200 14200 E AndroidRuntime:        at com.theoplayer.ReactTHEOplayerViewManager.createViewInstance(ReactTHEOplayerViewManager.kt:21)
09-13 14:39:08.959 14200 14200 E AndroidRuntime:        at com.theoplayer.ReactTHEOplayerViewManager.createViewInstance(ReactTHEOplayerViewManager.kt:15)
09-13 14:39:08.959 14200 14200 E AndroidRuntime:        at com.facebook.react.uimanager.ViewManager.createViewInstance(ViewManager.java:176)
09-13 14:39:08.959 14200 14200 E AndroidRuntime:        at com.facebook.react.uimanager.ViewManager.createView(ViewManager.java:108)
09-13 14:39:08.959 14200 14200 E AndroidRuntime:        at com.facebook.react.uimanager.NativeViewHierarchyManager.createView(NativeViewHierarchyManager.java:281)
09-13 14:39:08.959 14200 14200 E AndroidRuntime:        at com.facebook.react.uimanager.UIViewOperationQueue$CreateViewOperation.execute(UIViewOperationQueue.java:194)
09-13 14:39:08.959 14200 14200 E AndroidRuntime:        at com.facebook.react.uimanager.UIViewOperationQueue$DispatchUIFrameCallback.dispatchPendingNonBatchedOperations(UIViewOperationQueue.java:1121)
09-13 14:39:08.959 14200 14200 E AndroidRuntime:        at com.facebook.react.uimanager.UIViewOperationQueue$DispatchUIFrameCallback.doFrameGuarded(UIViewOperationQueue.java:1092)
09-13 14:39:08.959 14200 14200 E AndroidRuntime:        at com.facebook.react.uimanager.GuardedFrameCallback.doFrame(GuardedFrameCallback.java:29)
09-13 14:39:08.959 14200 14200 E AndroidRuntime:        at com.facebook.react.modules.core.ReactChoreographer$ReactChoreographerDispatcher.doFrame(ReactChoreographer.java:175)
09-13 14:39:08.959 14200 14200 E AndroidRuntime:        at com.facebook.react.modules.core.ChoreographerCompat$FrameCallback$1.doFrame(ChoreographerCompat.java:85)
09-13 14:39:08.959 14200 14200 E AndroidRuntime:        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1337)
09-13 14:39:08.959 14200 14200 E AndroidRuntime:        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1348)
09-13 14:39:08.959 14200 14200 E AndroidRuntime:        at android.view.Choreographer.doCallbacks(Choreographer.java:952)
09-13 14:39:08.959 14200 14200 E AndroidRuntime:        at android.view.Choreographer.doFrame(Choreographer.java:878)
09-13 14:39:08.959 14200 14200 E AndroidRuntime:        at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1322)
09-13 14:39:08.959 14200 14200 E AndroidRuntime:        at android.os.Handler.handleCallback(Handler.java:958)
09-13 14:39:08.959 14200 14200 E AndroidRuntime:        at android.os.Handler.dispatchMessage(Handler.java:99)
09-13 14:39:08.959 14200 14200 E AndroidRuntime:        at android.os.Looper.loopOnce(Looper.java:205)
09-13 14:39:08.959 14200 14200 E AndroidRuntime:        at android.os.Looper.loop(Looper.java:294)
09-13 14:39:08.959 14200 14200 E AndroidRuntime:        at android.app.ActivityThread.main(ActivityThread.java:8177)
09-13 14:39:08.959 14200 14200 E AndroidRuntime:        at java.lang.reflect.Method.invoke(Native Method)
09-13 14:39:08.959 14200 14200 E AndroidRuntime:        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552)
09-13 14:39:08.959 14200 14200 E AndroidRuntime:        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:971)
09-13 14:39:08.959 14200 14200 E AndroidRuntime: Caused by: java.lang.ClassNotFoundException: Didn't find class "com.theoplayer.android.api.ads.ima.GoogleImaAdEventType" on path: DexPathList[[zip file "/data/app/~~0KHYm17b6M6s8j335WpX9g==/com.backscreenapp-WUYdiOVsUFYMFbs4BVN09g==/base.apk"],nativeLibraryDirectories=[/data/app/~~0KHYm17b6M6s8j335WpX9g==/com.backscreenapp-WUYdiOVsUFYMFbs4BVN09g==/lib/arm64, /data/app/~~0KHYm17b6M6s8j335WpX9g==/com.backscreenapp-WUYdiOVsUFYMFbs4BVN09g==/base.apk!/lib/arm64-v8a, /system/lib64, /system_ext/lib64]]
09-13 14:39:08.959 14200 14200 E AndroidRuntime:        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:259)
09-13 14:39:08.959 14200 14200 E AndroidRuntime:        at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
09-13 14:39:08.959 14200 14200 E AndroidRuntime:        at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
09-13 14:39:08.959 14200 14200 E AndroidRuntime:        ... 26 more
`

I don't have any kind of extensions added, I'm not using IMA SDK, just barebone basic config, this happened when I upgraded android SDK from 7.6.0 to latest

**Comment by tvanlaerhoven** [comment]
@Veryyapeee We'll investigate, thanks!

**Comment by tvanlaerhoven** [comment]
@Veryyapeee could you check in Android Studio if the native THEOplayer module versions that are resolved are all actually 8.X? In the "Project" view, under "External Libraries".
Maybe also check that you re not pinning the native SDK to an earlier version.

![Screenshot 2024-09-18 at 15 37 14](https://github.com/user-attachments/assets/bf7272d8-a44c-479e-9cff-ed999f62d208)

**Comment by tvanlaerhoven** [comment]
@Veryyapeee Ah yes, most probably indeed. I'll try with our expo sample app. Could you meanwhile check as well by adding THEOplayer as a plugin in your Expo's `app.json`?

```
"plugins": ["react-native-theoplayer"]
```

We have a plugin that adds a local dependency as a Maven module. Expo skips it without the plugin.

**Comment by Veryyapeee** [comment]
> @Veryyapeee Ah yes, most probably indeed. I'll try with our expo sample app. Could you meanwhile check as well by adding THEOplayer as a plugin in your Expo's `app.json`?
> 
> ```
> "plugins": ["react-native-theoplayer"]
> ```
> 
> We have a plugin that adds a local dependency as a Maven module. Expo skips it without the plugin.

Yup, I know that, and we are using that since day 1

**Comment by tvanlaerhoven** [comment]
@Veryyapeee there was an issue with transitive dependencies related to IMA. A fix is in review, we'll make a release shortly.
