### ISSUE TITLE
v1.6.1 iOS build error

### ISSUE THREAD

**Issue by KestasVenslauskas** [THEOplayer/react-native-theoplayer#46]
I'm getting build errors while updating from 1.2.0 to 1.6.1

EDIT: Just checked 1.6.0 works fine.

<img width="1510" alt="Screenshot at Oct 26 22-07-26" src="https://user-images.githubusercontent.com/52245569/198115451-755e2117-5770-4199-a117-2834ae7f0d3f.png">

**Comment by wvanhaevre** [comment]
Thanks for reporting. I will check this out.

**Comment by wvanhaevre** [comment]
@KestasVenslauskas I am not able to reproduce your issue.
The reason why you can only see this issue on v1.6.1 is that we introduce the usage of the MultiplatformDRMConfiguration on the iOS bridge in that release. Our react-native-theoplayer package depends on the THEOplayerSDK-basic as you can see in your node_modules/react-native-theoplayer/react-native-theoplayer.podspec:
`s.dependency "THEOplayerSDK-basic"`
After a pod install, you should currently get a 4.2.0 THEOplayer pod. You can verify in 
`[your project]/ios/Pods/THEOplayerSDK-basic/Frameworks/THEOplayerSDK-basic/THEOplayerSDK.xcframework/ios-arm64/THEOplayerSDK.framework/info.plist`
that should contain 
`CFBundleShortVersionString = "4.2.0";`
If not, make sure to update your pod repo with `pod repo update`

**Comment by tvanlaerhoven** [comment]
@KestasVenslauskas , any update on this from your side?
