### ISSUE TITLE
Ad Error: Integration Type

### ISSUE THREAD

**Issue by jlmcdonald** [THEOplayer/react-native-theoplayer#47]
Trying out the feature/ad_events branch to get VAST/VMAP support. I'm getting an AD_ERROR related to the `integration` attribute. If I leave it off, the error message complains that I haven't defined the CSAI integration:

`{"errorCode": "AD_ERROR", "errorMessage": "Missing CSAI integration: "}`

If I set it to `theo` (which the docs state is the default), the error is:

`{"errorCode": "AD_ERROR", "errorMessage": "Unsupported CSAI integration: theo"}

If I set it to `google-ima` then the error is:

`{"errorCode": "AD_ERROR", "errorMessage": "Google IMA support not enabled."}`

I recognize this branch is a work in progress and under active development and it may very well be that it just isn't ready for use yet. I just want to check to make sure I'm not doing something wrong (i.e. if I need to include the IMA plugin on my own, for example).

**Comment by tvanlaerhoven** [comment]
Hey @jlmcdonald! 
Indeed this branch relies on changes/fixes in the underlying iOS & Android SDKs that need to go public first, before we can make these features public on the react-native package. Also, for iOS you'll need an SDK that has the IMA feature enabled.
Are you already in contact with our product team? If not, it's best to go through them in case early access is needed.

**Comment by jlmcdonald** [comment]
Yes, I can go through them. Just wanted to verify there wasn't a problem on my end first. Thx.
