### ISSUE TITLE
Player events callback bug (onReadyStateChange & onTimeUpdate ) after seek

### ISSUE THREAD

**Issue by janvandertaelen** [THEOplayer/react-native-theoplayer#54]
Currently on version 1.7.1.

We have a situation where we switch from live to an open recording
When this happens the source changes and we seek to the last position ( paused property is set to true ). 

We notice that the onReadyStateChange is not called when the source changes with the paused prop set to true. The onTimeUpdate callback is also not triggered when the paused prop is set to true.

if we briefly change the paused property from true to false it works but it includes a dirty hack on our side.

Is this intended behaviour?  For us it seems more logic to trigger all the callbacks after a seek disregard of the paused property set too true or false.

**Comment by wvanhaevre** [comment]
When changing the source on the player you 'reset' the player. This implies that the ready_state is also reset en will only be updated once new ready_states are reached, i.e. playback is started/continued. The same applies to onTimeUpdate events. This event indicates changes in the 'currentTime' of the player, so when the player is in a 'playing' mode, updating the currentTime. From the described use-case it sounds like you set a new source and pause the player. As a result ready_state changes and timeUpdate events will start to appear once the player starts playing again. If you would do a seek without changing the source, it would indeed make sense to trigger these events as they indicate a state change on the current player instance.
What is the use-case that needs to be handled by the events you are expecting? Maybe a different approach could provide the required info?

**Comment by wvanhaevre** [comment]
Does the simple workaround of briefly starting and stopping playback of the second stream (e.g. till first timeUpdate event) to show the first frame suffice for now to support your use case?

**Comment by tvanlaerhoven** [comment]
@janvandertaelen did the work-around help you out?

**Comment by janvandertaelen** [comment]
Workaround works but is not ideal.

`setPlayerIsPaused(false);
      setTimeout(() => {
        setPlayerIsPaused(true);
      }, 1);`

we are doing this when a new source is loaded. If you can fix that after a new source is loaded that onReadyStateChange is called it would remove our dirty hack.
