### ISSUE TITLE
Youbora integration

### ISSUE THREAD

**Issue by danychi** [THEOplayer/react-native-theoplayer#58]
Hi there guys, 

We are interested in using Youbora on `AndroidTV` and `tvOS` in react-native. From the official [THEOPlayer docs](https://docs.theoplayer.com/how-to-guides/02-analytics/03-youbora.md) I see that Youbora is not available on tvOS. I saw that in order to integrate it at least with AndroidTV, I need to add the `analytics` key to any of the video sources, but this doesn't seem to work yet with `react-native-theoplayer`.

Do you have any recommendations to make it work? 

Thank you!! 🤗

**Comment by tvanlaerhoven** [comment]
Hey @danychi, Youbora support for the react-native SDK is currently not yet on our roadmap. It is best to contact our product team to make sure it gets on there.

**Comment by tvanlaerhoven** [comment]
@danychi we recently released the Youbora connector:

https://www.npmjs.com/package/@theoplayer/react-native-analytics-youbora
