### ISSUE TITLE
Feature Request: Use Document Picture-in-Picture Web API

### ISSUE THREAD

**Issue by beaufortfrancois** [THEOplayer/react-native-theoplayer#66]
Users should be able to use THEOplayer in a Picture-in-Picture window, not just the HTML video inside the web player. 

![image](https://user-images.githubusercontent.com/634478/216599998-6b6570d9-39f9-4a8d-92fd-2a0720af84cd.png)

Before the Document Picture-in-Picture API, it was only possible to put an HTML `<video>` element into a Picture-in-Picture window. This new API makes it possible to open an always-on-top window that can be populated with arbitrary HTML content. It is available as an origin trial starting in Chrome 111 on desktop.

```js
async function togglePictureInPicture() {
  // Close Picture-in-Picture window if any.
  if (documentPictureInPicture.window) {
    documentPictureInPicture.window.close();
    return;
  }

  // Open a Picture-in-Picture window.
  const pipWindow = await documentPictureInPicture.requestWindow({
    initialAspectRatio: 640 / 360,
    copyStyleSheets: true,
  });

  // Move video to the Picture-in-Picture window.
  const video = document.querySelector("#video");
  pipWindow.document.body.append(video);

  // Listen for the PiP closing event to move the video back.
  pipWindow.addEventListener("unload", (event) => {
    const videoContainer = document.querySelector("#videoContainer");
    const pipVideo = event.target.querySelector("#video");
    videoContainer.append(pipVideo);
  });
}
```

Documentation:
- https://developer.chrome.com/blog/the-future-of-picture-in-picture/
- https://developer.chrome.com/docs/web-platform/document-picture-in-picture/
- https://github.com/WICG/document-picture-in-picture/issues

**Comment by beaufortfrancois** [comment]
@wvanhaevre What do you think of this API?

**Comment by tvanlaerhoven** [comment]
Hey @beaufortfrancois ! Thank you for this code sample. We're currently adding a presentation API to switch between PiP and inline playback across all platforms.

**Comment by beaufortfrancois** [comment]
I'm glad to learn that! Is this presentation API available already publicly?

**Comment by tvanlaerhoven** [comment]
@beaufortfrancois not yet, but it will be added this quarter.

**Comment by beaufortfrancois** [comment]
Do you have plans to add Document Picture-in-Picture API support as part of the upcoming presentation API or "just" the Picture-in-Picture API for `video`?

**Comment by tvanlaerhoven** [comment]
@beaufortfrancois Yes, in the upcoming 2.0.0 version, the PiP feature is available on all platforms through a single API.

https://github.com/THEOplayer/react-native-theoplayer/blob/feature/2.0.0/doc/pip.md

**Comment by beaufortfrancois** [comment]
It is not clear to me whether the Web part uses the Document Picture-in-Picture API, or the Picture-in-Picture API for video. Can you clarify in https://github.com/THEOplayer/react-native-theoplayer/blob/feature/2.0.0/doc/pip.md#web?

**Comment by beaufortfrancois** [comment]
@tvanlaerhoven (gentle ping)

**Comment by tvanlaerhoven** [comment]
Hi @beaufortfrancois! In contrast to what I commented above, we decided to add the 'classic' PiP API using `requestPictureInPicture` first and keep the Document Picture-in-Picture API as a future addition.
It does open up a lot of extra features, so we are definitely keen on including it.
