### ISSUE TITLE
Module not found when building iOS release with custom framework

### ISSUE THREAD

**Issue by vidangelci** [THEOplayer/react-native-theoplayer#75]
When loading in a custom framework (from the theoplayer portal) for iOS (to get Google IMA support), We follow the instructions found here to set up the xcframework in a location that can be found by the compiler. The react-native app build completes just fine in debug; however, when running a release build (using something like `npx react-native run-ios --configuration Release`  is what we normally do, but we also see the issue when trying to build an archive through xcode), the build process fails even though the location of the framework hasn't changed (swift throws a "module not found" error when trying to run `import THEOplayerSDK`). Are there additional steps needed to get it to do a release build with the custom xcframework?

We are running this on a machine with an Apple M1 chip but have also tried an Intel chip. It just seems unable to find the sdk ... we have tried both the "npm local paths" approach, tried patching the npm module, tried forking and pulling in ourselves from github, etc.

**Comment by wvanhaevre** [comment]
We recently updated the versions we support for the Google IMA SDK that is used by out theoplayer. That change will land in one of the next releases. 
Up till that release, the react-native-theoplayer package still locks to on an older Google IMA SDK which does not have arm64 simulator (M1) support.
Could you verify if excluding arm64 simulator support from your project prevents the error you see?
You can do this by adding the exclusion to the settings of your project targets:
<img width="699" alt="Screenshot 2023-02-15 at 10 51 34" src="https://user-images.githubusercontent.com/56914507/218993595-394c7822-ab3d-499b-b7ac-5454098ce4dc.png">

**Comment by jlmcdonald** [comment]
No, unfortunately this is not the issue. I've already been excluding the arm64 arch for both debug and release. And as I mentioned, the debug build works just fine. It only can no longer find the THEOplayer sdk when I try to to a release build. Also note that, as I said, it is ONLY when I am trying to import a custom SDK from the portal (the xcframework, following the instructions in the README) do I run into this problem. If I don't use the custom framework, I can build a release version without problems. 

I suspect it has something to do with react native no longer being able to locate the xcframework in the npm module's folder when doing a release build (I have tried using npm local paths, as suggested, I have tried putting the custom xcframework right into the node_modules/react-native-theoplayer folder, and I have also forked the project into our own repo, customized it there, and then made that the dependency ... all to no avail)).

**Comment by tvanlaerhoven** [comment]
@vidangelci @jlmcdonald is this still a valid issue?

**Comment by vidangelci** [comment]
Sorry for not keeping up-to-date here. We were able to work around it with patch-package and some custom logic for discovering the xcframework. It's hackish but got us to be able to deploy. On our next build, I'll revisit to see if it's still a problem now that both Theoplayer and Google IMA have better support for the M1 emulator architecture. For now it's ok to close.
