### ISSUE TITLE
Android and Android TV not playing content in version 1.8.2

### ISSUE THREAD

**Issue by danychi** [THEOplayer/react-native-theoplayer#91]
Hello there!

We can build Android and Android TV again after the patch in version 1.8.2, but it seems we cannot play any content on those platforms. tvOS and iOS are working perfectly though. 

I attach a picture of the Android TV
 
![IMG_7852 Large](https://user-images.githubusercontent.com/45874461/230051600-57c95a9f-93bb-4be6-bbc6-03f6daebbfdf.jpeg)

**Comment by tvanlaerhoven** [comment]
@danychi we've had issues with Android's dependencies picking up v5.0.0 of the SDK. An updated react-native-theoplayer v1.8.3 is in the making.

**Comment by tvanlaerhoven** [comment]
@danychi was the issue resolved for you?

**Comment by tvanlaerhoven** [comment]
@danychi closing this issue for now; let us know in case of any other problems.
