### ISSUE TITLE
New V2 breaks web builds

### ISSUE THREAD

**Issue by MwareSolutons** [THEOplayer/react-native-theoplayer#94]
Compiled with problems:X

ERROR in ./node_modules/react-native-theoplayer/node_modules/react-native-svg/lib/module/ReactNativeSVG.web.js 8:22-24

export 'createElement' (imported as 'cE') was not found in 'react-native' (possible exports: AccessibilityInfo, ActivityIndicator, Alert, Animated, AppRegistry, AppState, Appearance, BackHandler, Button, CheckBox, Clipboard, DeviceEventEmitter, DeviceInfo, Dimensions, DrawerLayoutAndroid, Easing, FlatList, I18nManager, Image, ImageBackground, InputAccessoryView, InteractionManager, Keyboard, KeyboardAvoidingView, LayoutAnimation, Linking, LogBox, Modal, NativeEventEmitter, NativeModules, PanResponder, PermissionsAndroid, Picker, PixelRatio, Platform, Pressable, ProgressBar, RefreshControl, SafeAreaView, ScrollView, SectionList, Settings, Share, StatusBar, StyleSheet, Switch, Systrace, TVEventHandler, Text, TextInput, ToastAndroid, Touchable, TouchableHighlight, TouchableNativeFeedback, TouchableOpacity, TouchableWithoutFeedback, UIManager, Vibration, View, VirtualizedList, YellowBox, findNodeHandle, processColor, render, unmountComponentAtNode, unstable_createElement, useColorScheme, useLocaleContext, useWindowDimensions)

**Comment by tvanlaerhoven** [comment]
@MwareSolutons Yes, you'll have to add this alias as well in your webpack:

resolve: {
    alias: {
      'react-native-svg': 'react-native-svg-web'
    },
  }

We'll try to find a different solution in import-level for this.

**Comment by tvanlaerhoven** [comment]
@MwareSolutons does this work for you?

**Comment by MwareSolutons** [comment]
Yes that fixed it for us.
